[package]
name = "keyboard"
version = "0.1.0"
edition = "2021"

[dependencies]
input = "0.9.0"
libc = "0.2.155"
rodio = "0.18.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
